import { X, BookOpen, Plus } from "lucide-react";
import { useTranslation } from "react-i18next";
import { useState } from "react";
import type { MonsterData } from "../../types";
import MonsterListItem from "./MonsterListItem";
import MonsterEditModal from "./MonsterEditModal";

type Props = {
  isOpen: boolean;
  monsters: MonsterData[];
  canLoadToForm?: boolean;
  onClose: () => void;
  onLoadToForm?: (monster: MonsterData) => void;
  onUpdate: (id: string, updated: MonsterData) => void;
  onCreate: (
    monster: Omit<MonsterData, "id" | "createdAt" | "updatedAt">
  ) => void;
  onDelete: (id: string) => void;
};

export default function MonsterLibraryModal({
  isOpen,
  monsters,
  canLoadToForm = false,
  onClose,
  onLoadToForm,
  onUpdate,
  onCreate,
  onDelete,
}: Props) {
  const { t } = useTranslation(["common", "forms"]);

  const newMonsterTemplate: MonsterData = {
    id: "", // Will be generated by storage provider
    name: "",
    hp: "10",
    ac: "10",
    imageUrl: "",
    str: "10",
    dex: "10",
    con: "10",
    int: "10",
    wis: "10",
    cha: "10",
    createdAt: 0,
    updatedAt: 0,
  };

  const [editingMonster, setEditingMonster] = useState<MonsterData | undefined>(
    undefined
  );
  const [isCreating, setIsCreating] = useState(false);

  if (!isOpen) return null;

  const handleUpdateMonster = (updated: MonsterData) => {
    onUpdate(updated.id, updated);
    setEditingMonster(undefined);
  };

  const handleCreateMonster = (newMonster: MonsterData) => {
    onCreate(newMonster);
    setIsCreating(false);
  };

  const onSave = isCreating ? handleCreateMonster : handleUpdateMonster;
  const onCancel = isCreating
    ? () => {
        setIsCreating(false);
      }
    : () => {
        setEditingMonster(undefined);
      };
  const monster = isCreating ? newMonsterTemplate : editingMonster;
  const editModal =
    isCreating || editingMonster ? (
      <MonsterEditModal
        monster={monster ?? newMonsterTemplate}
        onSave={onSave}
        onCancel={onCancel}
        isCreating = {isCreating}
      />
    ) : undefined;

  return (
    <>
      {/* Backdrop */}
      <div
        className="!mt-0 fixed inset-0 bg-black/50 backdrop-blur-sm z-40"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div className="bg-slate-800 rounded-lg border border-slate-700 max-w-4xl w-full max-h-[90vh] shadow-xl flex flex-col">
          {/* Header */}
          <div className="flex items-center justify-between p-4 md:p-6 border-b border-slate-700">
            <div className="flex items-center gap-3">
              <BookOpen className="w-6 h-6 text-purple-400" />
              <h2 className="text-xl md:text-2xl font-bold text-white">
                Monster Library
              </h2>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setIsCreating(true)}
                className="bg-green-600 hover:bg-green-700 text-white px-3 md:px-4 py-2 rounded transition font-medium flex items-center gap-2"
                title="Create New Monster"
              >
                <Plus className="w-5 h-5" />
                <span className="hidden sm:inline">New Monster</span>
              </button>
              <button
                onClick={onClose}
                className="text-slate-400 hover:text-white transition"
              >
                <X className="w-6 h-6" />
              </button>
            </div>
          </div>

          {/* Content - Scrollable Area */}
          <div className="flex-1 overflow-y-auto p-4 md:p-6 max-h-[60vh]">
            {monsters.length === 0 ? (
              <div className="text-center text-slate-400 py-12">
                <BookOpen className="w-16 h-16 mx-auto mb-4 opacity-50" />
                <p className="text-lg">No monsters in your library yet.</p>
                <p className="text-sm mt-2">
                  Save monsters from the combat form to build your collection!
                </p>
              </div>
            ) : (
              <div className="space-y-2 pr-2">
                {monsters.map((monster) => (
                  <MonsterListItem
                    key={monster.id}
                    monster={monster}
                    canLoadToForm={canLoadToForm}
                    onLoadToForm={onLoadToForm}
                    onEdit={setEditingMonster}
                    onDelete={onDelete}
                  />
                ))}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="border-t border-slate-700 p-4 md:p-6">
            <button
              onClick={onClose}
              className="w-full md:w-auto bg-slate-700 hover:bg-slate-600 text-white px-6 py-2 rounded transition font-medium"
            >
              {t("common:actions.close")}
            </button>
          </div>
        </div>
      </div>
      {editModal}
    </>
  );
}
